spring:
  application:
    name: kafka-elk

  # ========= MONGO DB =========== #
  #data:
  #  mongodb:
  #    database: monitor-db
  #    host: localhost
  #    port: 27017
  #    password: monitor-password
  #    username: monitor-user

  kafka:
    topic-name: packetbeat-topic
    bootstrap-servers: localhost:9092
    consumer:
      group-id: java-group
      auto-offset-reset: earliest

######### LOGGING ###############
logging:
  level:
    root: WARN
    org.springframework.web: ERROR
    org.springframework.security: ERROR
    org.hibernate: ERROR
    com.datapipeline.kafkaelk: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
  # file in: C:/tmp/rfi-management.log
  file:
    name: logs/kafka-elk.log
  pattern:
    file: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n"
