ARG UBUNTU_VERSION

FROM ubuntu:${UBUNTU_VERSION}

# package required
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        openjdk-8-jre \
        openssh-server \
        curl \
        libcap2-bin \
        && rm -rf /var/lib/apt/lists/*

ARG BEAT_VERSION

# packetbeat
RUN curl -L -O https://artifacts.elastic.co/downloads/beats/packetbeat/packetbeat-${BEAT_VERSION}-amd64.deb && \
    dpkg -i packetbeat-${BEAT_VERSION}-amd64.deb && \
    rm -f packetbeat-${BEAT_VERSION}-amd64.deb

# auditbeat
RUN curl -L -O https://artifacts.elastic.co/downloads/beats/auditbeat/auditbeat-${BEAT_VERSION}-amd64.deb && \
    dpkg -i auditbeat-${BEAT_VERSION}-amd64.deb && \
    rm -f auditbeat-${BEAT_VERSION}-amd64.deb

# Add capabilities for auditbeat
RUN setcap cap_audit_control,cap_audit_read+ep /usr/share/auditbeat/bin/auditbeat

ARG TOMCAT_MACRO_VERSION
ARG TOMCAT_VERSION

# Tomcat 6
RUN curl -L -O https://archive.apache.org/dist/tomcat/tomcat-${TOMCAT_MACRO_VERSION}/v${TOMCAT_VERSION}/bin/apache-tomcat-${TOMCAT_VERSION}.tar.gz && \
    tar xvzf apache-tomcat-${TOMCAT_VERSION}.tar.gz && \
    rm -f apache-tomcat-${TOMCAT_VERSION}.tar.gz && \
    mv apache-tomcat-${TOMCAT_VERSION} /usr/local/tomcat && \
    chmod +x /usr/local/tomcat/bin/*

# ssh
RUN mkdir /var/run/sshd && \
    echo 'root:root' | chpasswd && \
    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
    

COPY config/packetbeat.yml /etc/packetbeat/packetbeat.yml
COPY config/auditbeat.yml /etc/auditbeat/auditbeat.yml
COPY config/tomcat-users.xml /usr/local/tomcat/conf/tomcat-users.xml

ENV CATALINA_HOME /usr/local/tomcat
ENV PATH $CATALINA_HOME/bin:$PATH

EXPOSE 8080

CMD service ssh start && catalina.sh run
