version: '3'

services:
  # start mongo services
  mongo_db:
    hostname: mongo_db
    image: mongo:${MONGO_VERSION}
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: monitor-db
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - mongo-db_data-container:/data/db 
      - ${PWD}/config/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks: 
      - dmz-network 
  
  mongo-express:
    container_name: mongo-express
    restart: always
    image: mongo-express:${MONGO_EXPRESS_VERSION}
    depends_on:
      - mongo_db 
    networks: 
      - dmz-network
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo_db
      - ME_CONFIG_MONGODB_ADMINUSERNAME=monitor-user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=monitor-user
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    ports:
      - '8081:8081'

  # start kafka services
  zookeeper:
    image: 'bitnami/zookeeper:${ZOOKEPEER_VERSION}'
    ports:
      - '2181:2181'
    container_name: 'zookeeper'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - dmz-network

  kafka:
    image: 'bitnami/kafka:${KAFKA_VERSION}'
    container_name: 'kafka'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:29092,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CREATE_TOPICS=packetbeat-topic:1:1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper
    networks:
      - dmz-network

  # start elk services
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION}
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata-vol:/usr/share/elasticsearch/data
    ports:
      - "9300:9300"
      - "9200:9200"
    networks:
      - dmz-network

  kibana:
    image: docker.elastic.co/kibana/kibana:${KIBANA_VERSION}
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9300"
    ports:
      - "5601:5601"
    networks:
      - dmz-network

  logstash:
    image: docker.elastic.co/logstash/logstash:${LOGSTASH_VERSION}
    container_name: logstash
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ${PWD}/config/logstash.conf:/etc/logstash/conf.d/logstash.conf
    ports:
      - "5000:5000"
    networks:
      - dmz-network

  packetbeat:
    image: docker.elastic.co/beats/packetbeat:${PACKETBEAT_VERSION}
    container_name: packetbeat
    user: root
    networks:
      - dmz-network
    volumes:
      - ${PWD}/packetbeat.yml:/usr/share/packetbeat/packetbeat.yml
      - packetbeat-vol:/usr/share/packetbeat/data
      #- /var/run/docker.sock:/var/run/docker.sock # vedere cosa è
    # vedere cosa è cap
    #cap_add:
    #  - NET_RAW
    #  - NET_ADMIN
    command: ["--strict.perms=false"] 


  # To add java container   

volumes:
  mongo-db_data-container:
  packetbeat-vol:
  esdata-vol:
    driver: local

networks:
  dmz-network:
    driver: bridge