FROM ubuntu:20.04

# package required
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        openjdk-8-jre \
        openssh-server \
        curl \
        auditd \
        libaudit-dev \
        libcap2-bin \
        && rm -rf /var/lib/apt/lists/*

# packetbeat
RUN curl -L -O https://artifacts.elastic.co/downloads/beats/packetbeat/packetbeat-7.14.0-amd64.deb && \
    dpkg -i packetbeat-7.14.0-amd64.deb && \
    rm -f packetbeat-7.14.0-amd64.deb

# auditbeat
RUN curl -L -O https://artifacts.elastic.co/downloads/beats/auditbeat/auditbeat-7.14.0-amd64.deb && \
    dpkg -i auditbeat-7.14.0-amd64.deb && \
    rm -f auditbeat-7.14.0-amd64.deb

# Add capabilities for auditbeat
RUN setcap cap_audit_control,cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_module,cap_sys_rawio,cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_boot,cap_sys_nice,cap_sys_resource,cap_sys_time,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap,cap_mac_override,cap_mac_admin,cap_syslog,cap_audit_read+ep /usr/share/auditbeat/bin/auditbeat    

# Tomcat 6
RUN curl -L -O https://archive.apache.org/dist/tomcat/tomcat-6/v6.0.53/bin/apache-tomcat-6.0.53.tar.gz && \
    tar xvzf apache-tomcat-6.0.53.tar.gz && \
    rm -f apache-tomcat-6.0.53.tar.gz && \
    mv apache-tomcat-6.0.53 /usr/local/tomcat && \
    chmod +x /usr/local/tomcat/bin/*

# ssh
RUN mkdir /var/run/sshd && \
    echo 'root:root' | chpasswd && \
    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
    

COPY packetbeat.yml /etc/packetbeat/packetbeat.yml
COPY auditbeat.yml /etc/auditbeat/auditbeat.yml
COPY tomcat-users.xml /usr/local/tomcat/conf/tomcat-users.xml

# RUN setcap 'CAP_NET_RAW+eip CAP_NET_ADMIN+eip' /usr/bin/packetbeat

ENV CATALINA_HOME /usr/local/tomcat
ENV PATH $CATALINA_HOME/bin:$PATH

EXPOSE 8080 22

CMD service ssh start && catalina.sh run