packetbeat.interfaces.device: any

packetbeat.protocols:
- type: http
  ports: [80, 8080, 8000, 5000, 8002, 8180]
- type: dns
  ports: [53]
- type: icmp
  enabled: true

packetbeat.flows:
  timeout: 30s
  period: 5s

packetbeat.modules:
- module: system
  sysctl.module: net
  period: 10s
  interfaces.device: any

output.elasticsearch:
  hosts: ["elasticsearch-mts:9200"]
  #index: "packetbeat-%{+yyyy.MM.dd}"

setup.dashboards.enabled: true
setup.dashboards.retry.enabled: true
setup.dashboards.retry.maximum: 0
setup.kibana:
  host: "kibana-mts:5601"